# Tips for developing on this file:
#
#  * To see what config currently applies, try a command like:
#
#      $ npx eslint --print-config src/convert.ts | less
#
#    or for a specific rule:
#
#      $ npx eslint --print-config src/convert.ts | jq '.rules["indent"]'
#
#    Especially handy for seeing the default or base setting, when we don't
#    configure a rule ourselves.
#
#  * A variation to canonicalize the config output for comparison:
#
#     $ npx eslint --print-config src/foo.ts | jq . --sorted >/tmp/foo.json
#     $ npx eslint --print-config src/bar.ts | jq . --sorted >/tmp/bar.json
#     $ git diff --no-index /tmp/{foo,bar}.json

env:
  node: true
  es2021: true
extends:
  - eslint:recommended
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'

rules:
  # Google has code: 80.  We have Prettier target 80 columns,
  # but allow an occasional line to go wider.
  max-len:
    - error
    - code: 90
      tabWidth: 2
      ignoreUrls: true

  # Formatting that we let Prettier handle
  operator-linebreak: off
  object-curly-spacing: off # Google has no spaces here
  quotes: off # Prettier wants `"it 'will'"`, not `'it \'will\''`.  Whatever.
  # For indent, I think I like the Google style better than Prettier's:
  #   - Indent function args and params by 4 spaces rather than 2
  #   - Ditto multi-line method chains
  #   - No silly bug on comment at the end of a switch case
  # But not enough to fight Prettier over it.
  indent: off

  # Rules we may want, but need tweaking options and/or migrating code
  no-redeclare: off

  # Rules we don't want
  require-jsdoc: off
  valid-jsdoc: off

overrides:
  - files: 't/**/*.d.ts'
    globals:
      JSX: readonly
    rules:
      # Allow some things in our test inputs that we don't in normal code.
      no-unused-vars: off
      no-var: off
      one-var: off
      no-octal: off
      no-loss-of-precision: off

      max-len:
        - error
        - code: 110
          tabWidth: 2
          ignoreUrls: true
