env:
  browser: true
  es2021: true
extends:
  - google
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"

rules:
  # Rules we don't want
  require-jsdoc: off
  valid-jsdoc: off

  # Rules we may want but require tweaking details and/or migrating code
  indent: off
  curly: off
  quotes: off
  operator-linebreak: off
  object-curly-spacing: off
  max-len: off
  no-throw-literal: off
  no-unused-vars: off

overrides:
  - files: "t/**/*.d.ts"
    rules:
      # Allow some things in our test inputs that we don't in normal code.
      no-var: off
      one-var: off
