# Tips for developing on this file:
#
#  * To see what config currently applies, try a command like:
#
#      $ npx eslint --print-config src/convert.ts | less
#
#    or for a specific rule:
#
#      $ npx eslint --print-config src/convert.ts | jq '.rules["indent"]'
#
#    Especially handy for seeing the default or base setting, when we don't
#    configure a rule ourselves.
#
#  * A variation to canonicalize the config output for comparison:
#
#     $ npx eslint --print-config src/foo.ts | jq . --sorted >/tmp/foo.json
#     $ npx eslint --print-config src/bar.ts | jq . --sorted >/tmp/bar.json
#     $ git diff --no-index /tmp/{foo,bar}.json

env:
  browser: true
  es2021: true
extends:
  - google
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"

rules:
  # Rules we don't want
  require-jsdoc: off
  valid-jsdoc: off

  # Rules we may want but require tweaking details and/or migrating code
  indent: off
  curly: off
  quotes: off
  operator-linebreak: off
  object-curly-spacing: off
  max-len: off
  no-throw-literal: off

overrides:
  - files: "t/**/*.d.ts"
    rules:
      # Allow some things in our test inputs that we don't in normal code.
      no-unused-vars: off
      no-var: off
      one-var: off
